---
title: Resources
subtitle: IDS:705 Principles of Machine Learning
toc: true
toc-expand: 2
number-sections: false
---

## Introductory books for machine learning
- [**An Introduction to Statistical Learning with Python**](https://www.statlearning.com/), by James, Witten, Hastie, and Tibshirani
- [**Understanding Deep learning**](https://udlbook.github.io/udlbook/) by Simon Prince
- Introduction to Data Mining, by Tan, Steinbach, Karpatne, and Kumar
- [**Pattern Recognition and Machine Learning**](https://www.microsoft.com/en-us/research/publication/pattern-recognition-machine-learning/), by Bishop
- [**Deep Learning**](https://www.deeplearningbook.org/), by Goodfellow, Bengio, and Courville
- [**Reinforcement Learning: An Introduction**](http://incompleteideas.net/book/the-book-2nd.html): An Introduction, by Sutton and Barto

## Math for machine learning
- [Mathematics for Machine Learning](https://mml-book.github.io/book/mml-book.pdf) by Deisenroth, Faisal, and Ong
- [Deep Learning](https://www.deeplearningbook.org/); Part I: Applied Math and Machine Learning Basics by Goodfellow, Bengio, and Courville
- [The Matrix Calculus You Need For Deep Learning](https://arxiv.org/pdf/1802.01528.pdf) by Parr and Howard
- [Dive Into Deep Learning](https://d2l.ai/chapter_appendix-mathematics-for-deep-learning/index.html); Appendix: Mathematics for Deep Learning by Weness, Hu, et al.

## Python Programming
The following online courses on Coursera are a 5-part series on Python programming:

- [Python Programming Fundamentals](https://www.coursera.org/learn/python-programming-fundamentals/)
- [Data Science with NumPy, Sets, and Dictionaries](https://www.coursera.org/learn/numpy-data-science/)
- [Pandas for Data Science](https://www.coursera.org/learn/pandas-data-science/)
- [Designing Larger Python Programs for Data Science](https://www.coursera.org/learn/python-design-for-data-science/)
- [Data Visualization and Modeling in Python](https://www.coursera.org/learn/python-data-modeling/)
